module.exports = {
  jsxSingleQuote: true,
  singleQuote: true,
  semi: true,
  tabWidth: 2,
  trailingComma: 'all',
  printWidth: 100,
  bracketSameLine: false,
  useTabs: false,
  arrowParens: 'always',
  endOfLine: 'auto',
  plugins: ['@ianvs/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
  tailwindAttributes: ['classNames'],
  tailwindFunctions: ['clsx', 'cn'],
  importOrder: [
    '^react',
    '<BUILT_IN_MODULES>',
    '<THIRD_PARTY_MODULES>',
    '^@/lib',
    '^@/context',
    '^@/components',
    '^@/app',
    '^@/pages',
    '^@/utils',
    '^@/assets',
    '^@/types',
    '^[.]',
    '^(?!.*[.]css$)[./].*$',
    '.css$',
  ],
};
